### ISSUE TITLE
Parameters are not supported for mermaid diagrams 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cupid#69]
#### Describe the bug
Cupid creates a non-usable mermaid diagram when an AsyncAPI file has a channel using parameters. 

#### How to Reproduce
Given the following file, it generates an unusable mermaid diagram:
```yaml
asyncapi: 2.2.0
info:
  title: Comments Service
  version: 1.0.0
  description: This service is in charge of processing all the events related to comments.
servers:
  mosquitto:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
    bindings:
      mqtt:
        clientId: comment-service
channels:
  comment/{commentId}/changed:
    description: Sends the new count to the broker after it has been updated in the database.
    parameters: 
      commentId:
        schema: 
          type: string
    subscribe: 
      message:
        payload: true
```  
Which gives the output: 

```
graph TD
 server1[(mqtt://test.mosquitto.org)]
CommentsService -- comment/{commentId}/changed --> server1
```
#### Expected behavior
Expected mermaid diagram channels to be wrapped with `"`.

```
graph TD
 server1[(mqtt://test.mosquitto.org)]
CommentsService -- "comment/{commentId}/changed" --> server1
```
