### ISSUE TITLE
Use channel server constraints

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cupid#70]
#### Reason/Context
In the new version of AsyncAPI 2.2.0 you are allowed to define which servers a channel is designated towards. This is instead of using the default behavior of being related towards all defined servers.

Example AsyncAPI document:

```yaml
asyncapi: 2.2.0
info:
  title: Website Backend
  version: 1.0.0
servers:
  websiteWebSocketServer:
    url: ws://mycompany.com/ws
    protocol: ws
  mosquitto:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
    bindings:
      mqtt:
        clientId: websocketServer
channels:
  comment/liked:
    description: Notify all the services that a comment has been liked.
    servers: ['mosquitto']
    subscribe: 
      message:
        payload: true
  like/comment:
    description: When a comment like is received from the frontend.
    servers: ['websiteWebSocketServer']
    publish: 
      message:
        payload: true
```

In this example I would expect that `like/comment` is only related to the `websiteWebSocketServer` and `comment/liked` towards `mosquitto`.
